Force LF eol for scripts to fix standard_init_linux.go:219 error. Fix genesis.json to fix eip150Block error.  Fix Dockerfile to use pm2 instead of /usr/bin/pm2